#!/bin/bash

sub_dir="blog"

echo ""
if [ ! -d ${OPENSHIFT_DATA_DIR}uploads ]; then
    echo "${OPENSHIFT_DATA_DIR}uploads not found, making it."
    mkdir ${OPENSHIFT_DATA_DIR}uploads
fi
# Add multisite upload dir
if [ ! -d $OPENSHIFT_DATA_DIR/blogs.dir ]; then
    echo "$OPENSHIFT_DATA_DIR/blogs.dir not found, making it."
    mkdir $OPENSHIFT_DATA_DIR/blogs.dir
fi
echo ""
ln -sf ${OPENSHIFT_DATA_DIR}blogs.dir ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/
echo ""
echo "symbolically linking ${OPENSHIFT_DATA_DIR}blogs.dir -> ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/"
echo ""
ln -sf ${OPENSHIFT_DATA_DIR}uploads   ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/
echo ""
echo "symbolically linking ${OPENSHIFT_DATA_DIR}uploads -> ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/"
echo ""

set -e
if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi
if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi
# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from wp_commentmeta;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo
    echo "Database schema not yet added, WordPress is ready for install by visiting the site."
else
    echo "Database already configured."
fi
echo ""
