#!/bin/bash

#set this variable value to something else if you plan on changing the subdirectory name. refer to the readme in the repo root directory
#for more info
sub_dir="blog"

echo ""

if [ ! -d ${OPENSHIFT_DATA_DIR}${sub_dir}/wp-content/themes/ ]; then
    echo "Pre-Stop hook - ${OPENSHIFT_DATA_DIR}${sub_dir}/wp-content/themes/ not found, making it."
    mkdir -p ${OPENSHIFT_DATA_DIR}${sub_dir}/wp-content/themes/
fi

cp -fR ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/themes/* ${OPENSHIFT_DATA_DIR}${sub_dir}/wp-content/themes
echo "Pre-Stop hook - copying files from ${OPENSHIFT_REPO_DIR}${sub_dir}/wp-content/themes/    TO    ${OPENSHIFT_DATA_DIR}${sub_dir}/wp-content/themes/"
echo ""
